name: Laravel DDD CI

on: push

jobs:
    php-unit-tests:
        name: PHP - Unit Tests
        runs-on: ubuntu-20.04
        if: (!contains(github.ref, 'refs/heads/master') && !contains(github.ref, 'refs/heads/staging'))

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: PHP Setup
                uses: ./.github/actions/php-setup

            -   name: Run tests
                run: php artisan test --testsuite=Unit
                shell: bash

    php-integration-tests-1:
        name: PHP - Integration Tests 1/3 - Application Layer
        runs-on: ubuntu-20.04
        if: (!contains(github.ref, 'refs/heads/master') && !contains(github.ref, 'refs/heads/staging'))

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: laravel_ddd_testing
                ports:
                    - 3306:3306

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: PHP Setup
              uses: ./.github/actions/php-setup

            -   name: Wait for MySQL
                    run: |
                        while ! mysqladmin ping --host=127.0.0.1 --silent; do
                          sleep 1
                        done

            - name: Run tests
              run: php artisan test --parallel --testsuite=Integration1
              shell: bash

    php-integration-tests-2:
        name: PHP - Integration Tests 2/3 - Domain Layer
        runs-on: ubuntu-20.04
        if: (!contains(github.ref, 'refs/heads/master') && !contains(github.ref, 'refs/heads/staging'))

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: laravel_ddd_testing
                ports:
                    - 3306:3306

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: PHP Setup
                uses: ./.github/actions/php-setup

            -   name: Wait for MySQL
                    run: |
                        while ! mysqladmin ping --host=127.0.0.1 --silent; do
                          sleep 1
                        done

            -   name: Run tests
                run: php artisan test --parallel --testsuite=Integration2
                shell: bash

    php-integration-tests-3:
        name: PHP - Integration Tests 3/3 - Infrastructure Layer
        runs-on: ubuntu-20.04
        if: (!contains(github.ref, 'refs/heads/master') && !contains(github.ref, 'refs/heads/staging'))

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: laravel_ddd_testing
                ports:
                    - 3306:3306

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: PHP Setup
                uses: ./.github/actions/php-setup

            -   name: Wait for MySQL
                    run: |
                        while ! mysqladmin ping --host=127.0.0.1 --silent; do
                          sleep 1
                        done

            -   name: Run tests
                run: php artisan test --parallel --testsuite=Integration3
                shell: bash
